### ISSUE TITLE
how to Install it? 

### ISSUE THREAD

**Issue by amin616** [neomax7/cloudflare-warp-installer#1]
I need this on my manjaro but I'm not a programming pro like u. how can I install the package? 
Should I use the codes in something like atom and then try to execute it?

**Comment by neomax7** [comment]
Hi,  @amin616 
first open up the terminal 
1.  `git clone https://github.com/neomax7/cloudflare-warp-installer.git`
2.  `cd cloudflare-warp-installer`
4. ` ./installer.sh`
5. `sudo systemctl enable --now warp-svc.service`
done
now you can start connection like 
`warp-cli connect` 
or 
`warp-cli disconnect`

updated comments for better visibility

**Comment by neomax7** [comment]
closing

**Comment by amin616** [comment]
which repo do I need to clone? I understand what it is to clone a repository but as I mentioned earlier I'm an amateur 
thanks anyway

**Comment by neomax7** [comment]
hi @amin616 
to clone a repo
you have to install "git" package to begin with.
and to run this installer, you need "curl" package
try below for manjaro
`pamac install curl git`
then do 
`git clone https://github.com/neomax7/cloudflare-warp-installer.git`
after that you can follow the instruction from the previous comments

**Comment by amin616** [comment]
![Screenshot_20240225_122005](https://github.com/neomax7/cloudflare-warp-installer/assets/45890912/1a72a747-8b07-4de2-ab6a-00094dbd3928)
I did all that but after installation and starting the service and connecting it. again with warp-cli status I see this frustrating message: disconnected and the reason is manual disconnection. I live in Iran and I want to use this as an anticensorship. 
it seems something disconnecting it in the background am I correct? Can I fix it?

**Comment by neomax7** [comment]
are you using systemd-resolved? it's currently interfering with it.
do 
`sudo systemctl status systemd-resolved.service`
if you see its active then you have to do two steps everytime you use it
1. `warp-cli connect`
2. `sudo systemctl stop systemd-resolved.service`
after that it should work
on disconnect you gotta do reverse
1. `warp-cli disconnect`
2. `sudo systemctl start systemd-resolved.service`

**Comment by amin616** [comment]
![Screenshot_20240225_134315](https://github.com/neomax7/cloudflare-warp-installer/assets/45890912/b80a94d2-d036-49da-998f-55add025b5bd)
I did that unfortunately it's not working. a few months ago I was using this warp smoothly and I think it's banned by the government AI censorship devices. 
after I enter warp-cli connect and see the status the status says manual disconnection but even then I don't have access to anything and my internet wouldn't be connected unless I enter warp-cli disconnect. it's pretty tough these days to have access to a free net in Iran. 
Thanks for your help anyway. at least I've learnt to clone a git directory.

**Comment by amin616** [comment]
can I install this on Debian distro? I've already tried and it says error on line 14

**Comment by neomax7** [comment]
> can I install this on Debian distro? I've already tried and it says error on line 14

yes you can, you have to install binutils package in that case.

thank you

**Comment by amin616** [comment]
How can I uninstall this package using terminal?

**Comment by neomax7** [comment]
> How can I uninstall this package using terminal? 

Hi, 

you can uninstall by doing followings

sudo rm /bin/warp-*
sudo rm /lib/systemd/system/warp-svc.service
sudo systemctl daemon-reload
