### ISSUE TITLE
You have been added to AUR

### ISSUE THREAD

**Issue by dhupee** [neomax7/cloudflare-warp-installer#2]
hey i just want to inform you that you have been added to co-maintainer in Warp's AUR repo

**Comment by neomax7** [comment]
oh wow thank you! will definitely check

**Comment by dhupee** [comment]
This is Leon's(solatis) reply after I email him directly about update or adding co-maintainer

```
Hi there,

Thanks, yes I've been trying to find another maintainer for the package, as I moved away from using it. Several times someone took over (a little bit) and then they stopped maintaining it.

What would be the right process to proceed?

Regards,

Leon Mergen
```

so he add you as one of the maintainers, hope you can help to maintain it

thx
